@extends('plantilla')
@section('content')
    <div class="row">
        <div class="col-16">
            <h1>Página de inicio</h1>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, dolorum. Consequuntur sequi repellat tempora cupiditate atque ex assumenda voluptates? Omnis ab temporibus officia, vero perspiciatis et dignissimos nemo modi quaerat! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Obcaecati est, perspiciatis reiciendis suscipit exercitationem voluptatum veritatis, accusantium commodi expedita cumque molestias deserunt magni rem architecto! Accusantium molestias consequatur vel praesentium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, dolorum. Consequuntur sequi repellat tempora cupiditate atque ex assumenda voluptates? Omnis ab temporibus officia, vero perspiciatis et dignissimos nemo modi quaerat! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Obcaecati est, perspiciatis reiciendis suscipit exercitationem voluptatum veritatis, accusantium commodi expedita cumque molestias deserunt magni rem architecto! Accusantium molestias consequatur vel praesentium.</div>
        <div class="col-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, dolorum. Consequuntur sequi repellat tempora cupiditate atque ex assumenda voluptates? Omnis ab temporibus officia, vero perspiciatis et dignissimos nemo modi quaerat! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Obcaecati est, perspiciatis reiciendis suscipit exercitationem voluptatum veritatis, accusantium commodi expedita cumque molestias deserunt magni rem architecto! Accusantium molestias consequatur vel praesentium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, dolorum. Consequuntur sequi repellat tempora cupiditate atque ex assumenda voluptates? Omnis ab temporibus officia, vero perspiciatis et dignissimos nemo modi quaerat! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Obcaecati est, perspiciatis reiciendis suscipit exercitationem voluptatum veritatis, accusantium commodi expedita cumque molestias deserunt magni rem architecto! Accusantium molestias consequatur vel praesentium.</div>
        <div class="col-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, dolorum. Consequuntur sequi repellat tempora cupiditate atque ex assumenda voluptates? Omnis ab temporibus officia, vero perspiciatis et dignissimos nemo modi quaerat! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Obcaecati est, perspiciatis reiciendis suscipit exercitationem voluptatum veritatis, accusantium commodi expedita cumque molestias deserunt magni rem architecto! Accusantium molestias consequatur vel praesentium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, dolorum. Consequuntur sequi repellat tempora cupiditate atque ex assumenda voluptates? Omnis ab temporibus officia, vero perspiciatis et dignissimos nemo modi quaerat! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Obcaecati est, perspiciatis reiciendis suscipit exercitationem voluptatum veritatis, accusantium commodi expedita cumque molestias deserunt magni rem architecto! Accusantium molestias consequatur vel praesentium.</div>
    </div>
@endsection